[phases.setup]
nixPkgs = ["...", "jdk17"]

[phases.build]
cmds = ["cd backend && ./mvnw clean package -DskipTests"]

[start]
cmd = "java -Dserver.port=$PORT -jar backend/target/*.jar --spring.profiles.active=railway"
