services:
  - type: web
    name: pasoxpaso-backend
    runtime: docker
    region: oregon
    plan: free
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: render
      - key: JWT_SECRET
        value: miClaveSecretaSuperSeguraParaJWT2024PasoxPasoEcommerce
      - key: FRONTEND_URL
        value: https://tu-frontend.vercel.app
      - key: DATABASE_URL
        fromDatabase:
          name: pasoxpaso-db
          property: connectionString

databases:
  - name: pasoxpaso-db
    databaseName: pasoxpaso
    user: pasoxpaso
    plan: free
    region: oregon
